/**
 * Generates a TypeScript file that references every symbol the recipes import from
 * Angular, so `tsc` proves each one actually exists in the real package.
 *
 * This is the cheap half of compile verification: it cannot check that a snippet is
 * semantically right, but it does catch the failure mode that has bitten this project
 * twice — a recipe naming an API that does not exist (`Control` vs `FormField`).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const { allRecipes } = await import(join(here, '../dist/core/recipes.js'));

/** Modules whose exports we can verify by importing them. */
const VERIFIABLE = new Set([
  '@angular/forms/signals',
  '@angular/forms/signals/compat',
  '@angular/core',
  '@angular/core/rxjs-interop',
]);

const importRe = /import\s+(type\s+)?\{([^}]+)\}\s+from\s+'([^']+)'/g;

/**
 * module -> Map<symbol, isTypeOnly>.
 *
 * Types and values need different proofs: a value can be referenced in an array, a type
 * needs an alias. Getting this wrong makes the harness fail on its own scaffolding rather
 * than on a real problem.
 */
const wanted = new Map();
const provenance = new Map();

for (const recipe of allRecipes()) {
  for (const [, typeOnlyImport, names, module] of recipe.after.matchAll(importRe)) {
    if (!VERIFIABLE.has(module)) continue;
    const entry = wanted.get(module) ?? new Map();
    for (const raw of names.split(',')) {
      const trimmed = raw.trim();
      if (trimmed === '') continue;
      const isType = typeOnlyImport !== undefined || /^type\s/.test(trimmed);
      const name = trimmed.replace(/^type\s+/, '').split(/\s+as\s+/)[0].trim();
      if (name === '') continue;
      // A symbol seen as a value anywhere is a value.
      entry.set(name, (entry.get(name) ?? true) && isType);
      const key = `${module}#${name}`;
      provenance.set(key, [...(provenance.get(key) ?? []), recipe.construct]);
    }
    wanted.set(module, entry);
  }
}

const lines = [
  '/* GENERATED by verify/generate.mjs — do not edit. */',
  '/* Referencing every symbol the recipes import, so tsc proves each one exists. */',
  '/* eslint-disable */',
  '',
];

let total = 0;
for (const [module, entry] of [...wanted].sort()) {
  const sorted = [...entry.keys()].sort();
  total += sorted.length;
  const spec = sorted.map((n) => (entry.get(n) === true ? `type ${n}` : n)).join(', ');
  lines.push(`import { ${spec} } from '${module}';`);
}
lines.push('');
lines.push('// Values: referenced so an unused-import rule cannot hide a miss.');
lines.push('export const referencedValues: unknown[] = [');
for (const [module, entry] of [...wanted].sort()) {
  for (const name of [...entry.keys()].sort()) {
    if (entry.get(name) === true) continue;
    const used = provenance.get(`${module}#${name}`) ?? [];
    lines.push(`  ${name}, // ${module} — used by: ${[...new Set(used)].join(', ')}`);
  }
}
lines.push('];');
lines.push('');
lines.push('// Type-only exports need no reference: the import above is itself the proof.');
lines.push('// tsc reports TS2305 for a name a module does not export, used or not.');
mkdirSync(join(here, 'generated'), { recursive: true });
writeFileSync(join(here, 'generated', 'symbols.ts'), lines.join('\n'));

console.log(`generated ${String(total)} symbol references across ${String(wanted.size)} modules`);
for (const [module, names] of [...wanted].sort()) {
  console.log(`  ${String(names.size).padStart(3)}  ${module}`);
}
